# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Messafge(object):
    def setupUi(self, Messafge):
        Messafge.setObjectName("Messafge")
        Messafge.resize(240, 331)
        icon = QtGui.QIcon.fromTheme("Dark")
        Messafge.setWindowIcon(icon)
        Messafge.setStyleSheet("QMainWindow{\n"
"background: #393939;\n"
"}\n"
"\n"
"QPushButton{\n"
"background: #5A5A5B;\n"
"border-radius: 8px;\n"
"color: black;\n"
"}\n"
"QPushButton:hover{\n"
"background: #D1AF00;\n"
"}\n"
"\n"
"QPlainTextEdit{\n"
"background: #454546;\n"
"border-radius: 5px;\n"
"}\n"
"\n"
"QTextBrowser{\n"
"background: #454546;\n"
"border-radius: 5px;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(Messafge)
        self.centralwidget.setObjectName("centralwidget")
        self.tabW = QtWidgets.QTabWidget(self.centralwidget)
        self.tabW.setGeometry(QtCore.QRect(0, 0, 241, 331))
        self.tabW.setMouseTracking(True)
        self.tabW.setStyleSheet("color: black\n"
"")
        self.tabW.setObjectName("tabW")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.encrypt = QtWidgets.QPushButton(self.tab)
        self.encrypt.setGeometry(QtCore.QRect(2, 267, 231, 32))
        self.encrypt.setObjectName("encrypt")
        self.encrypt_input = QtWidgets.QPlainTextEdit(self.tab)
        self.encrypt_input.setGeometry(QtCore.QRect(-3, 0, 241, 121))
        self.encrypt_input.setObjectName("encrypt_input")
        self.encrypt_out = QtWidgets.QTextBrowser(self.tab)
        self.encrypt_out.setGeometry(QtCore.QRect(-3, 130, 241, 131))
        self.encrypt_out.setObjectName("encrypt_out")
        self.tabW.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.decrypt_input = QtWidgets.QPlainTextEdit(self.tab_2)
        self.decrypt_input.setGeometry(QtCore.QRect(-3, 0, 241, 121))
        self.decrypt_input.setObjectName("decrypt_input")
        self.decrypt_out = QtWidgets.QTextBrowser(self.tab_2)
        self.decrypt_out.setGeometry(QtCore.QRect(-3, 130, 241, 131))
        self.decrypt_out.setObjectName("decrypt_out")
        self.decrypt = QtWidgets.QPushButton(self.tab_2)
        self.decrypt.setGeometry(QtCore.QRect(2, 267, 231, 32))
        self.decrypt.setObjectName("decrypt")
        self.tabW.addTab(self.tab_2, "")
        Messafge.setCentralWidget(self.centralwidget)

        self.retranslateUi(Messafge)
        self.tabW.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Messafge)

    def retranslateUi(self, Messafge):
        _translate = QtCore.QCoreApplication.translate
        Messafge.setWindowTitle(_translate("Messafge", "Messafge"))
        self.encrypt.setText(_translate("Messafge", "Encrypt"))
        self.tabW.setTabText(self.tabW.indexOf(self.tab), _translate("Messafge", "Encrypt"))
        self.decrypt.setText(_translate("Messafge", "Decrypt"))
        self.tabW.setTabText(self.tabW.indexOf(self.tab_2), _translate("Messafge", "Decrypt"))
